tasks:
  - command: yarn run watch
    init: yarn install && yarn run build
  - name: ConfigAlias
    command: echo 'alias pj="npx projen"' >> ~/.bashrc && echo 'alias cdk="npx cdk"' >> ~/.bashrc
  - name: Initialize & Configure AWS
    command: bash $GITPOD_REPO_ROOT/gitpod_scripts/gitpod_configure_aws.sh
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - AmazonWebServices.aws-toolkit-vscode