tasks:
  - command: run npm install 
    init: npm install
  - name: Initialize & Configure AWS
    command: bash $GITPOD_REPO_ROOT/gitpod_scripts/gitpod_configure_aws.sh
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - AmazonWebServices.aws-toolkit-vscode
